export const styles = {
  page: {
    fontFamily: "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial",
    background: "#0b0b0b",
    color: "#f5f5f5",
    minHeight: "100vh",
  },
  header: {
    padding: "18px 18px 10px 18px",
    borderBottom: "1px solid #2a2a2a",
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
  },
  h1: { margin: 0, fontSize: 20, letterSpacing: 0.2 },
  badge: {
    border: "1px solid",
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 12,
    background: "rgba(255,255,255,0.06)",
  },
  headerActions: { display: "flex", gap: 12, alignItems: "center" },
  toggle: { fontSize: 13, color: "#d4d4d4", userSelect: "none" },
  primaryBtn: {
    background: "#ffffff",
    border: "1px solid #e5e5e5",
    color: "#0b0b0b",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 700,
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 14,
    padding: 14,
  },
  card: {
    background: "#111111",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    padding: 14,
    boxShadow: "0 8px 20px rgba(0,0,0,0.45)",
    minHeight: 280,
  },
  cardWide: {
    gridColumn: "1 / -1",
    background: "#111111",
    border: "1px solid #2a2a2a",
    borderRadius: 16,
    padding: 14,
    boxShadow: "0 8px 20px rgba(0,0,0,0.45)",
    minHeight: 320,
  },
  h2: { margin: "0 0 10px 0", fontSize: 14, color: "#f5f5f5" },
  h3: { margin: "0 0 8px 0", fontSize: 13, color: "#f5f5f5" },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  editBtn: {
    borderRadius: 999,
    border: "1px solid #2a2a2a",
    background: "#161616",
    color: "#f5f5f5",
    padding: "4px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  textarea: {
    width: "100%",
    height: 220,
    resize: "vertical",
    borderRadius: 12,
    border: "1px solid #2a2a2a",
    background: "#0f0f0f",
    color: "#f5f5f5",
    padding: 12,
    outline: "none",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  help: { margin: "10px 0 0 0", fontSize: 12, color: "#bdbdbd" },
  gridRows: { display: "flex", flexDirection: "column", gap: 10 },
  gridRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 2fr) auto",
    gap: 8,
    alignItems: "center",
  },
  gridInput: {
    borderRadius: 10,
    border: "1px solid #2a2a2a",
    background: "#0f0f0f",
    color: "#f5f5f5",
    padding: "8px 10px",
    outline: "none",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12,
  },
  rowActions: { display: "flex", justifyContent: "flex-end", marginTop: 10 },
  addBtn: {
    borderRadius: 10,
    border: "1px solid #2a2a2a",
    background: "#161616",
    color: "#f5f5f5",
    padding: "6px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  rowBtn: {
    borderRadius: 10,
    border: "1px solid #2a2a2a",
    background: "#0b0b0b",
    color: "#e5e5e5",
    padding: "6px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  uploadBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 10px",
    borderRadius: 10,
    border: "1px solid #2a2a2a",
    background: "#0f0f0f",
    cursor: "pointer",
    fontSize: 12,
    color: "#e5e5e5",
    userSelect: "none",
  },
  errorBox: {
    marginTop: 12,
    borderRadius: 12,
    border: "1px solid #c2410c",
    background: "rgba(194,65,12,0.08)",
    padding: 12,
  },
  outputGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 360px",
    gap: 12,
    alignItems: "start",
  },
  treePane: {
    borderRadius: 14,
    border: "1px solid #2a2a2a",
    background: "#0f0f0f",
    padding: 10,
    minHeight: 260,
    overflow: "auto",
  },
  inspectorPane: {
    borderRadius: 14,
    border: "1px solid #2a2a2a",
    background: "#0f0f0f",
    padding: 12,
    minHeight: 260,
    overflow: "auto",
  },
  placeholder: {
    padding: 18,
    borderRadius: 14,
    border: "1px dashed #2a2a2a",
    color: "#bdbdbd",
    background: "#0f0f0f",
  },
  placeholderSmall: { color: "#bdbdbd", fontSize: 12 },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 10,
    cursor: "pointer",
  },
  treeRowSelected: {
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.2)",
  },
  disclosure: {
    width: 22,
    height: 22,
    borderRadius: 8,
    border: "1px solid #2a2a2a",
    background: "#161616",
    color: "#f5f5f5",
    cursor: "pointer",
  },
  disclosureSpacer: { display: "inline-block", width: 22 },
  treeLabel: { fontSize: 12.5, color: "#f5f5f5" },
  treeRange: { marginLeft: "auto", fontSize: 11, color: "#bdbdbd" },
  kvRow: { display: "grid", gridTemplateColumns: "80px 1fr", gap: 10, marginBottom: 8 },
  kvKey: { fontSize: 12, color: "#bdbdbd" },
  kvVal: { fontSize: 12, color: "#f5f5f5" },
  smallLabel: { fontSize: 11, color: "#bdbdbd", marginBottom: 6 },
  pre: {
    margin: 0,
    padding: 10,
    borderRadius: 12,
    border: "1px solid #2a2a2a",
    background: "#0b0b0b",
    fontSize: 11.5,
    overflow: "auto",
    color: "#f5f5f5",
  },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" },
  tokenList: { display: "flex", flexWrap: "wrap", gap: 8 },
  tokenChip: {
    display: "inline-flex",
    gap: 8,
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid #2a2a2a",
    background: "#161616",
    fontSize: 12,
  },
  miniMuted: { fontSize: 11, color: "#bdbdbd" },
  footer: {
    padding: 14,
    borderTop: "1px solid #2a2a2a",
    color: "#bdbdbd",
  },
  muted: { fontSize: 12 },
};
