export const styles = {
  page: {
    fontFamily: "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial",
    background: "#0b1220",
    color: "#e5e7eb",
    minHeight: "100vh",
  },
  header: {
    padding: "18px 18px 10px 18px",
    borderBottom: "1px solid #1f2a44",
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
  },
  h1: { margin: 0, fontSize: 20, letterSpacing: 0.2 },
  badge: {
    border: "1px solid",
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 12,
  },
  headerActions: { display: "flex", gap: 12, alignItems: "center" },
  toggle: { fontSize: 13, color: "#cbd5e1", userSelect: "none" },
  primaryBtn: {
    background: "#2563eb",
    border: "1px solid #1d4ed8",
    color: "white",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 700,
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 14,
    padding: 14,
  },
  card: {
    background: "#0f172a",
    border: "1px solid #1f2a44",
    borderRadius: 16,
    padding: 14,
    boxShadow: "0 8px 20px rgba(0,0,0,0.25)",
    minHeight: 280,
  },
  cardWide: {
    gridColumn: "1 / -1",
    background: "#0f172a",
    border: "1px solid #1f2a44",
    borderRadius: 16,
    padding: 14,
    boxShadow: "0 8px 20px rgba(0,0,0,0.25)",
    minHeight: 320,
  },
  h2: { margin: "0 0 10px 0", fontSize: 14, color: "#e2e8f0" },
  h3: { margin: "0 0 8px 0", fontSize: 13, color: "#e2e8f0" },
  textarea: {
    width: "100%",
    height: 220,
    resize: "vertical",
    borderRadius: 12,
    border: "1px solid #223055",
    background: "#0b1020",
    color: "#e5e7eb",
    padding: 12,
    outline: "none",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  help: { margin: "10px 0 0 0", fontSize: 12, color: "#94a3b8" },
  uploadBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 10px",
    borderRadius: 10,
    border: "1px solid #223055",
    background: "#0b1020",
    cursor: "pointer",
    fontSize: 12,
    color: "#cbd5e1",
    userSelect: "none",
  },
  errorBox: {
    marginTop: 12,
    borderRadius: 12,
    border: "1px solid #7f1d1d",
    background: "rgba(127,29,29,0.18)",
    padding: 12,
  },
  outputGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 360px",
    gap: 12,
    alignItems: "start",
  },
  treePane: {
    borderRadius: 14,
    border: "1px solid #1f2a44",
    background: "#0b1020",
    padding: 10,
    minHeight: 260,
    overflow: "auto",
  },
  inspectorPane: {
    borderRadius: 14,
    border: "1px solid #1f2a44",
    background: "#0b1020",
    padding: 12,
    minHeight: 260,
    overflow: "auto",
  },
  placeholder: {
    padding: 18,
    borderRadius: 14,
    border: "1px dashed #2b3a63",
    color: "#94a3b8",
    background: "#0b1020",
  },
  placeholderSmall: { color: "#94a3b8", fontSize: 12 },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 10,
    cursor: "pointer",
  },
  treeRowSelected: {
    background: "rgba(37,99,235,0.18)",
    border: "1px solid rgba(37,99,235,0.35)",
  },
  disclosure: {
    width: 22,
    height: 22,
    borderRadius: 8,
    border: "1px solid #223055",
    background: "#0f172a",
    color: "#cbd5e1",
    cursor: "pointer",
  },
  disclosureSpacer: { display: "inline-block", width: 22 },
  treeLabel: { fontSize: 12.5, color: "#e2e8f0" },
  treeRange: { marginLeft: "auto", fontSize: 11, color: "#94a3b8" },
  kvRow: { display: "grid", gridTemplateColumns: "80px 1fr", gap: 10, marginBottom: 8 },
  kvKey: { fontSize: 12, color: "#94a3b8" },
  kvVal: { fontSize: 12, color: "#e2e8f0" },
  smallLabel: { fontSize: 11, color: "#94a3b8", marginBottom: 6 },
  pre: {
    margin: 0,
    padding: 10,
    borderRadius: 12,
    border: "1px solid #223055",
    background: "#050814",
    fontSize: 11.5,
    overflow: "auto",
    color: "#d1d5db",
  },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" },
  tokenList: { display: "flex", flexWrap: "wrap", gap: 8 },
  tokenChip: {
    display: "inline-flex",
    gap: 8,
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid #223055",
    background: "#0f172a",
    fontSize: 12,
  },
  miniMuted: { fontSize: 11, color: "#94a3b8" },
  footer: {
    padding: 14,
    borderTop: "1px solid #1f2a44",
    color: "#94a3b8",
  },
  muted: { fontSize: 12 },
};
