export const styles = {
  page: {
    fontFamily: "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial",
    background: "var(--bg)",
    color: "var(--text)",
    minHeight: "100vh",
  },
  header: {
    padding: "18px 18px 10px 18px",
    borderBottom: "none",
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
  },
  h1: { margin: 0, fontSize: 20, letterSpacing: 0.2 },
  badge: {
    border: "1px solid",
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 12,
    background: "var(--badge-bg)",
  },
  headerActions: { display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" },
  toggle: { fontSize: 13, color: "var(--muted-strong)", userSelect: "none" },
  primaryBtn: {
    background: "var(--primary-bg)",
    border: "1px solid var(--primary-border)",
    color: "var(--primary-text)",
    padding: "10px 14px",
    borderRadius: 10,
    fontWeight: 700,
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 14,
    padding: 14,
  },
  card: {
    background: "var(--card)",
    border: "none",
    borderRadius: 16,
    padding: 14,
    boxShadow: "var(--shadow)",
    minHeight: 280,
  },
  cardWide: {
    gridColumn: "1 / -1",
    background: "var(--card)",
    border: "1px solid var(--border)",
    borderRadius: 16,
    padding: 14,
    boxShadow: "var(--shadow)",
    minHeight: 320,
  },
  h2: { margin: "0 0 10px 0", fontSize: 14, color: "var(--text)" },
  h3: { margin: "0 0 8px 0", fontSize: 13, color: "var(--text)" },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  editBtn: {
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--chip)",
    color: "var(--text)",
    padding: "4px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  textarea: {
    width: "100%",
    height: 220,
    resize: "vertical",
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--panel)",
    color: "var(--text)",
    padding: 12,
    outline: "none",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  help: { margin: "10px 0 0 0", fontSize: 12, color: "#bdbdbd" },
  helpRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    alignItems: "center",
    flexWrap: "wrap",
  },
  gridRows: { display: "flex", flexDirection: "column", gap: 10 },
  gridRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 2fr) auto",
    gap: 8,
    alignItems: "center",
  },
  gridInput: {
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--panel)",
    color: "var(--text)",
    padding: "8px 10px",
    outline: "none",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: 12,
  },
  rowActions: { display: "flex", justifyContent: "flex-end", marginTop: 10 },
  addBtn: {
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--chip)",
    color: "var(--text)",
    padding: "6px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  rowBtn: {
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--panel-strong)",
    color: "var(--muted-strong)",
    padding: "6px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  uploadBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 10px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--panel)",
    cursor: "pointer",
    fontSize: 12,
    color: "var(--muted-strong)",
    userSelect: "none",
  },
  errorBox: {
    marginTop: 12,
    borderRadius: 12,
    border: "1px solid #c2410c",
    background: "rgba(194,65,12,0.08)",
    padding: 12,
  },
  outputGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 360px",
    gap: 12,
    alignItems: "start",
  },
  treePane: {
    borderRadius: 14,
    border: "none",
    background: "var(--panel)",
    padding: 10,
    minHeight: 260,
    overflow: "auto",
  },
  inspectorPane: {
    borderRadius: 14,
    border: "1px solid var(--border)",
    background: "var(--panel)",
    padding: 12,
    minHeight: 260,
    overflow: "auto",
  },
  placeholder: {
    padding: 18,
    borderRadius: 14,
    border: "1px dashed var(--border)",
    color: "var(--muted)",
    background: "var(--panel)",
  },
  placeholderSmall: { color: "var(--muted)", fontSize: 12 },
  treeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 10,
    cursor: "pointer",
  },
  treeRowSelected: {
    background: "var(--panel",
    border: "1px solid var(--row-selected-border)",
  },
  disclosure: {
    width: 22,
    height: 22,
    borderRadius: 8,
    border: "none",
    background: "var(--panel)",
    color: "var(--text)",
    cursor: "pointer",
  },
  disclosureSpacer: { display: "inline-block", width: 22 },
  treeLabel: { fontSize: 12.5, color: "var(--text)" },
  treeRange: { marginLeft: "auto", fontSize: 11, color: "var(--muted)" },
  kvRow: { display: "grid", gridTemplateColumns: "80px 1fr", gap: 10, marginBottom: 8 },
  kvKey: { fontSize: 12, color: "var(--muted)" },
  kvVal: { fontSize: 12, color: "var(--text)" },
  smallLabel: { fontSize: 11, color: "var(--muted)", marginBottom: 6 },
  pre: {
    margin: 0,
    padding: 10,
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--panel-strong)",
    fontSize: 11.5,
    overflow: "auto",
    color: "var(--text)",
  },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" },
  tokenList: { display: "flex", flexWrap: "wrap", gap: 8 },
  tokenChip: {
    display: "inline-flex",
    gap: 8,
    alignItems: "center",
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--chip)",
    fontSize: 12,
  },
  miniMuted: { fontSize: 11, color: "var(--muted)" },
  footer: {
    padding: 14,
    borderTop: "none",
    color: "var(--muted)",
  },
  muted: { fontSize: 12, color: "var(--muted)" },
};
